# Wrangler configuration file for portfolio project
main = ".open-next/worker.js"
name = "portfolio"
compatibility_date = "2025-04-12"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# KV Namespace binding for dynamic announcements
[[kv_namespaces]]
binding = "ANNOUNCEMENT"
id = "b428b1971ea44bed96b27499f277561e"

# Custom domain configuration
[[routes]]
pattern = "leolucadatri.io"
custom_domain = true

# If you want to add additional domains or subdomains
# [[routes]]
# pattern = "www.leolucadatri.io"
# custom_domain = true